# _HTTP_PORT= [Puerto de exposicion del api]
# _RUN_MODE= [Modo de ejecucion del API]

# Variables de la DB
# _PGUSER= [Usuario de DB]
# _PGPASS= [Contraseña del usuario de la db]
# _PGHOST= [URL, IP, DOMINIO,o ENDPOINT de la DB]
# _PGPORT= [Puerto de la DB]
# _PGDB= [Nombre de la DB]
# _PGSCHEMA= [Nombre del esquema de la DB]

appname = APIS The House Fit
httpport = ${APIS_THE_HOUSE_FIT_HTTP_PORT}
runmode = ${APIS_THE_HOUSE_FIT_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true

# Definicion de variables de entorno DB

PGuser= ${APIS_THE_HOUSE_FIT_PGUSER}
PGpass= ${APIS_THE_HOUSE_FIT_PGPASS}
PGhost= ${APIS_THE_HOUSE_FIT_PGHOST}
PGport= ${APIS_THE_HOUSE_FIT_PGPORT}
PGdb= ${APIS_THE_HOUSE_FIT_PGDB}
PGschema= ${APIS_THE_HOUSE_FIT_PGSCHEMA}