- Tabla: usuarios
CREATE TABLE "LOGIN"."usuarios" (
    "id_usuario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombres" varchar(100) NOT NULL,
    "apellidos" varchar(100) NOT NULL,
    "email" varchar(150) UNIQUE NOT NULL,
    "Fecha_nacimiento" datetime NOT NULL,
    "nacionalidad" varchar(80),
    "ciudad" varchar(100),
    "departamento" varchar(100),
    "direccion" varchar(255),
    "telefono" varchar(20),
    "activo" bool NOT NULL DEFAULT true,
    "Fecha_modificacion" timestamp NOT NULL DEFAULT now(),
    "Fecha_creacion" timestamp NOT NULL DEFAULT now()
);

-- Tabla: Administrador
CREATE TABLE "LOGIN"."Administrador" (
    "id_administrador" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre_gym" varchar(150),
    "nit" varchar(30),
    "anio_fundacion" int,
    "cantidad_clientes" int,
    "departamento" varchar(100),
    "ciudad" varchar(100),
    "direccion" varchar(255),
    "propietario_nombre" varchar(200),
    "telefono" varchar(20),
    "correo" varchar(150),
    "pagina_web" varchar(255),
    "firma" varchar(255),
    "fecha_firma" date,
    "estado" varchar(20) DEFAULT 'pendiente',
    "activo" bool NOT NULL DEFAULT true,
    "Fecha_modificacion" timestamp NOT NULL DEFAULT now(),
    "Fecha_creacion" timestamp NOT NULL DEFAULT now()
);

-- Tabla: Login
CREATE TABLE "LOGIN"."Login" (
    "Id_login" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "id_nombre" int NOT NULL,
    CONSTRAINT fk_login_usuarios FOREIGN KEY ("id_nombre") REFERENCES "LOGIN"."usuarios" ("id_usuario") ON DELETE CASCADE,
    "Rol" varchar(20) NOT NULL,
    "activo" bool NOT NULL DEFAULT true,
    "Fecha_modificacion" timestamp NOT NULL DEFAULT now(),
    "Fecha_creacion" timestamp NOT NULL DEFAULT now()
);

-- =========================================================
-- 1. RELACIÓN ENTRE LA TABLA LOGIN Y LA TABLA USUARIOS
-- =========================================================
-- Vincula el campo 'id_nombre' de Login con el 'id_usuario' de usuarios.
-- 'ON DELETE CASCADE' asegura que si se elimina un usuario, se borre su login automáticamente.

ALTER TABLE "LOGIN"."Login"
ADD CONSTRAINT fk_login_usuarios
FOREIGN KEY (id_nombre) 
REFERENCES "LOGIN".usuarios(id_usuario)
ON DELETE CASCADE
ON UPDATE CASCADE;


-- =========================================================
-- 2. RESTRICCIÓN DE UNICIDAD PARA EL LOGIN (RECOMENDADO)
-- =========================================================
-- Si tu lógica de negocio dicta que un usuario SOLO puede tener un rol/registro de login,
-- añade esta restricción para evitar que un 'id_usuario' se repita en la tabla "Login".

ALTER TABLE "LOGIN"."Login"
ADD CONSTRAINT unique_id_nombre UNIQUE (id_nombre);