-- Tabla: entrenadores
CREATE TABLE "entrenadores"."entrenadores" (
    "id_entrenadores" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_adminitrador" int UNIQUE NOT NULL,
    "cedula" varchar(20) UNIQUE,
    "descripcion" text,
    "especialidad" varchar(150),
    "gimnasio_id" int,
    "anios_experiencia" int,
    "foto_url" varchar(255),
    "Aprovacion_entrenador" boolean DEFAULT false,
    "Hoja_vida" varchar NOT NULL,
    "calificacion_prom" decimal(2,1) DEFAULT 0,
    "activo" bool NOT NULL DEFAULT true,
    "Fecha_modificacion" timestamp NOT NULL DEFAULT now(),
    "Fecha_creacion" timestamp NOT NULL DEFAULT now()
);

-- Tabla: entrenador_documentos
CREATE TABLE "entrenadores"."entrenador_documentos" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "entrenador_id" int NOT NULL,
    "Identificacion" varchar(80),
    "nombre_archivo" varchar(150),
    "creado_en" timestamp DEFAULT now(),
    "activo" bool NOT NULL DEFAULT true,
    "Fecha_modificacion" timestamp NOT NULL DEFAULT now(),
    "Fecha_creacion" timestamp NOT NULL DEFAULT now()
);

-- Tabla: solicitudes_entrenador
CREATE TABLE "entrenadores"."solicitudes_entrenador" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "usuario_id" int NOT NULL,
    "gimnasio_id" int NOT NULL,
    "nombres_apellidos" varchar(200),
    "cedula" varchar(20),
    "experiencia" text,
    "sobre_mi" text,
    "especialidad" varchar(150),
    "whatsapp" varchar(20),
    "correo" varchar(150),
    "direccion" varchar(255),
    "estado" varchar(20) DEFAULT 'enviado',
    "revisado_por" boolean,
    "revisado_en" timestamp,
    "creado_en" timestamp DEFAULT now(),
    "activo" bool NOT NULL DEFAULT true,
    "Fecha_modificacion" timestamp NOT NULL DEFAULT now(),
    "Fecha_creacion" timestamp NOT NULL DEFAULT now()
);


-- ====================================================================
-- SCRIPT DE ADICIÓN DE LLAVES FORÁNEAS (RELACIONES)
-- Base de datos: entrenadores
-- Esquema: entrenadores
-- ====================================================================

-- 1. Relación entre 'entrenador_documentos' y 'entrenadores'
-- Vincula la columna 'entrenador_id' con la llave primaria 'id_entrenadores'
ALTER TABLE entrenadores.entrenador_documentos
    ADD CONSTRAINT fk_entrenador_documentos_entrenador
    FOREIGN KEY (entrenador_id) 
    REFERENCES entrenadores.entrenadores (id_entrenadores)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

-- 2. NOTA SOBRE INTEGRACIÓN CON EL MICROSERVICIO DE LOGIN:
-- Si vas a relacionar las tablas con los otros esquemas o bases de datos,
-- aquí te dejo los scripts comentados por si los necesitas más adelante:

-- Relación de solicitudes_entrenador con la tabla usuarios (del módulo login)
-- ALTER TABLE entrenadores.solicitudes_entrenador
--     ADD CONSTRAINT fk_solicitudes_usuario
--     FOREIGN KEY (usuario_id) 
--     REFERENCES "LOGIN".usuarios (id_usuario)
--     ON UPDATE CASCADE
--     ON DELETE RESTRICT;

-- Relación de entrenadores con la tabla Administrador (del módulo login)
-- ALTER TABLE entrenadores.entrenadores
--     ADD CONSTRAINT fk_entrenadores_administrador
--     FOREIGN KEY (id_adminitrador) 
--     REFERENCES "LOGIN"."Administrador" (id_administrador)
--     ON UPDATE CASCADE
--     ON DELETE RESTRICT;