
CREATE SCHEMA IF NOT EXISTS "rutinas";

-- Tabla: grupos_musculares
CREATE TABLE "rutinas"."grupos_musculares" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre" varchar(80) NOT NULL,
    "descripcion" text,
    "activo" bool NOT NULL DEFAULT true,
    "Fecha_modificacion" timestamp NOT NULL DEFAULT now(),
    "Fecha_creacion" timestamp NOT NULL DEFAULT now()
);

-- Tabla: ejercicios
CREATE TABLE "rutinas"."ejercicios" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "grupo_muscular_id" int NOT NULL,
    "nombre" varchar(150) NOT NULL,
    "descripcion_corta" varchar(255),
    "descripcion_larga" text,
    "posicion_inicial" text,
    "ejecucion" text,
    "consejos" text,
    "nivel" varchar(20),
    "activo" bool NOT NULL DEFAULT true,
    "Fecha_modificacion" timestamp NOT NULL DEFAULT now(),
    "Fecha_creacion" timestamp NOT NULL DEFAULT now()
);

-- Tabla: rutinas
CREATE TABLE "rutinas"."rutinas" (
    "id_usuario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre" varchar(150) NOT NULL,
    "descripcion" text,
    "objetivo" varchar(100),
    "activo" bool NOT NULL DEFAULT true,
    "Fecha_modificacion" timestamp NOT NULL DEFAULT now(),
    "Fecha_creacion" timestamp NOT NULL DEFAULT now()


    -- Relación entre ejercicios y grupos musculares
    ALTER TABLE rutinas.ejercicios
    ADD CONSTRAINT fk_ejercicios_grupos_musculares
    FOREIGN KEY (grupo_muscular_id) 
    REFERENCES rutinas.grupos_musculares(id)
    ON DELETE CASCADE; -- Opcional: si borras un grupo, se borran sus ejercicios
);
