appname = apis_the_blog
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true

# Base de datos - usando variables de entorno
dbdriver = postgres
dbhost = ${APIS_THE_BLOG_PGHOST}
dbport = ${APIS_THE_BLOG_PGPORT}
dbuser = ${APIS_THE_BLOG_PGUSER}
dbpassword = ${APIS_THE_BLOG_PGPASS}
dbname = ${APIS_THE_BLOG_PGDB}