appname = apis_gimnasios
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true

dbdriver = postgres
dbhost = ${APIS_GIMNASIOS_PGHOST}
dbport = ${APIS_GIMNASIOS_PGPORT}
dbuser = ${APIS_GIMNASIOS_PGUSER}
dbpassword = ${APIS_GIMNASIOS_PGPASS}
dbname = ${APIS_GIMNASIOS_PGDB}