CREATE TABLE IF NOT EXISTS gimnasios.Sedes_gimnasios (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    nit VARCHAR(30) UNIQUE,
    descripcion TEXT,
    ciudad VARCHAR(100),
    departamento VARCHAR(100),
    direccion VARCHAR(255),
    correo VARCHAR(150),
    telefono VARCHAR(20),
    Agregar_img VARCHAR,
    Agregar_Sede VARCHAR,
    Aprovacion_entrenadores BOOLEAN DEFAULT false,
    calificacion_prom DECIMAL(2,1) DEFAULT 0,
    total_resenas INTEGER DEFAULT 0,
    activo BOOLEAN DEFAULT true,
    administrador_id INTEGER,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);