appname = the_house_fitt
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = postgres://postgres:postgres@127.0.0.1:5432/the_house_fitt?sslmode=disable&search_path=tienda



PGuser = ${THE_HOUSE_FITT_PGUSER}
PGpass = ${THE_HOUSE_FITT_PGPASS}
PGhost = ${THE_HOUSE_FITT_PGHOST}
PGport = ${THE_HOUSE_FITT_PGPORT}
PGdb = ${THE_HOUSE_FITT_PGDB}
PGschema = ${THE_HOUSE_FITT_PGSCHEMA}