appname = the_house_fitt
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = postgres://postgres:postgres@127.0.0.1:5432/the_house_fitt?sslmode=disable&search_path=tienda
